//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ConsoleApplication18.wsIntegracao {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSIntegracaoSoap", Namespace="http://tempuri.org/")]
    public partial class WSIntegracao : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthHeader authHeaderValueField;
        
        private System.Threading.SendOrPostCallback ConsultaTiposDocumentosOperationCompleted;
        
        private System.Threading.SendOrPostCallback GravarFolderCloudDocsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarFoldersOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSIntegracao() {
            this.Url = global::ConsoleApplication18.Properties.Settings.Default.ConsoleApplication18_wsIntegracao_WSIntegracao;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthHeader AuthHeaderValue {
            get {
                return this.authHeaderValueField;
            }
            set {
                this.authHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultaTiposDocumentosCompletedEventHandler ConsultaTiposDocumentosCompleted;
        
        /// <remarks/>
        public event GravarFolderCloudDocsCompletedEventHandler GravarFolderCloudDocsCompleted;
        
        /// <remarks/>
        public event ConsultarFoldersCompletedEventHandler ConsultarFoldersCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaTiposDocumentos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaTiposDocumentos(string CodCliente, string TipoFolder) {
            object[] results = this.Invoke("ConsultaTiposDocumentos", new object[] {
                        CodCliente,
                        TipoFolder});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaTiposDocumentosAsync(string CodCliente, string TipoFolder) {
            this.ConsultaTiposDocumentosAsync(CodCliente, TipoFolder, null);
        }
        
        /// <remarks/>
        public void ConsultaTiposDocumentosAsync(string CodCliente, string TipoFolder, object userState) {
            if ((this.ConsultaTiposDocumentosOperationCompleted == null)) {
                this.ConsultaTiposDocumentosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaTiposDocumentosOperationCompleted);
            }
            this.InvokeAsync("ConsultaTiposDocumentos", new object[] {
                        CodCliente,
                        TipoFolder}, this.ConsultaTiposDocumentosOperationCompleted, userState);
        }
        
        private void OnConsultaTiposDocumentosOperationCompleted(object arg) {
            if ((this.ConsultaTiposDocumentosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaTiposDocumentosCompleted(this, new ConsultaTiposDocumentosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GravarFolderCloudDocs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal GravarFolderCloudDocs(
                    decimal FolderId, 
                    int ClienteId, 
                    long UsuarioId, 
                    decimal TipoFolder, 
                    decimal Origem, 
                    string Indice01, 
                    string Indice02, 
                    string Indice03, 
                    string Indice04, 
                    string Indice05, 
                    string Indice06, 
                    string Observacao, 
                    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] Documento, 
                    string Extensao, 
                    decimal Classificacao, 
                    string Complemento, 
                    int Evento) {
            object[] results = this.Invoke("GravarFolderCloudDocs", new object[] {
                        FolderId,
                        ClienteId,
                        UsuarioId,
                        TipoFolder,
                        Origem,
                        Indice01,
                        Indice02,
                        Indice03,
                        Indice04,
                        Indice05,
                        Indice06,
                        Observacao,
                        Documento,
                        Extensao,
                        Classificacao,
                        Complemento,
                        Evento});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void GravarFolderCloudDocsAsync(
                    decimal FolderId, 
                    int ClienteId, 
                    long UsuarioId, 
                    decimal TipoFolder, 
                    decimal Origem, 
                    string Indice01, 
                    string Indice02, 
                    string Indice03, 
                    string Indice04, 
                    string Indice05, 
                    string Indice06, 
                    string Observacao, 
                    byte[] Documento, 
                    string Extensao, 
                    decimal Classificacao, 
                    string Complemento, 
                    int Evento) {
            this.GravarFolderCloudDocsAsync(FolderId, ClienteId, UsuarioId, TipoFolder, Origem, Indice01, Indice02, Indice03, Indice04, Indice05, Indice06, Observacao, Documento, Extensao, Classificacao, Complemento, Evento, null);
        }
        
        /// <remarks/>
        public void GravarFolderCloudDocsAsync(
                    decimal FolderId, 
                    int ClienteId, 
                    long UsuarioId, 
                    decimal TipoFolder, 
                    decimal Origem, 
                    string Indice01, 
                    string Indice02, 
                    string Indice03, 
                    string Indice04, 
                    string Indice05, 
                    string Indice06, 
                    string Observacao, 
                    byte[] Documento, 
                    string Extensao, 
                    decimal Classificacao, 
                    string Complemento, 
                    int Evento, 
                    object userState) {
            if ((this.GravarFolderCloudDocsOperationCompleted == null)) {
                this.GravarFolderCloudDocsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGravarFolderCloudDocsOperationCompleted);
            }
            this.InvokeAsync("GravarFolderCloudDocs", new object[] {
                        FolderId,
                        ClienteId,
                        UsuarioId,
                        TipoFolder,
                        Origem,
                        Indice01,
                        Indice02,
                        Indice03,
                        Indice04,
                        Indice05,
                        Indice06,
                        Observacao,
                        Documento,
                        Extensao,
                        Classificacao,
                        Complemento,
                        Evento}, this.GravarFolderCloudDocsOperationCompleted, userState);
        }
        
        private void OnGravarFolderCloudDocsOperationCompleted(object arg) {
            if ((this.GravarFolderCloudDocsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GravarFolderCloudDocsCompleted(this, new GravarFolderCloudDocsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarFolders", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultarFolders(decimal FolderId, string ClienteId, string TipoFolder, string Origem, string Indice01, string Indice02, string Indice03, string Indice04, string Indice05, string Indice06, string DataIni, string DataFim) {
            object[] results = this.Invoke("ConsultarFolders", new object[] {
                        FolderId,
                        ClienteId,
                        TipoFolder,
                        Origem,
                        Indice01,
                        Indice02,
                        Indice03,
                        Indice04,
                        Indice05,
                        Indice06,
                        DataIni,
                        DataFim});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarFoldersAsync(decimal FolderId, string ClienteId, string TipoFolder, string Origem, string Indice01, string Indice02, string Indice03, string Indice04, string Indice05, string Indice06, string DataIni, string DataFim) {
            this.ConsultarFoldersAsync(FolderId, ClienteId, TipoFolder, Origem, Indice01, Indice02, Indice03, Indice04, Indice05, Indice06, DataIni, DataFim, null);
        }
        
        /// <remarks/>
        public void ConsultarFoldersAsync(decimal FolderId, string ClienteId, string TipoFolder, string Origem, string Indice01, string Indice02, string Indice03, string Indice04, string Indice05, string Indice06, string DataIni, string DataFim, object userState) {
            if ((this.ConsultarFoldersOperationCompleted == null)) {
                this.ConsultarFoldersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarFoldersOperationCompleted);
            }
            this.InvokeAsync("ConsultarFolders", new object[] {
                        FolderId,
                        ClienteId,
                        TipoFolder,
                        Origem,
                        Indice01,
                        Indice02,
                        Indice03,
                        Indice04,
                        Indice05,
                        Indice06,
                        DataIni,
                        DataFim}, this.ConsultarFoldersOperationCompleted, userState);
        }
        
        private void OnConsultarFoldersOperationCompleted(object arg) {
            if ((this.ConsultarFoldersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarFoldersCompleted(this, new ConsultarFoldersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class AuthHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string keyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ConsultaTiposDocumentosCompletedEventHandler(object sender, ConsultaTiposDocumentosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaTiposDocumentosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaTiposDocumentosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GravarFolderCloudDocsCompletedEventHandler(object sender, GravarFolderCloudDocsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GravarFolderCloudDocsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GravarFolderCloudDocsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ConsultarFoldersCompletedEventHandler(object sender, ConsultarFoldersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarFoldersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarFoldersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591