//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication18
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURACAO
    {
        public int ID { get; set; }
        public string TIPO { get; set; }
        public bool Ativo { get; set; }
        public Nullable<bool> Padrao { get; set; }
    }
}
