//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication18
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public int ID { get; set; }
        public int ModeloId { get; set; }
        public string NomeDocumento { get; set; }
        public string Valor { get; set; }
        public Nullable<int> PalavraId { get; set; }
        public string column_name { get; set; }
    
        public virtual Modelo Modelo { get; set; }
        public virtual Palavras Palavras { get; set; }
        public virtual Documento Documento1 { get; set; }
        public virtual Documento Documento2 { get; set; }
    }
}
