//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication18
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentocaptura
    {
        public int id { get; set; }
        public string caminhoEntrada { get; set; }
        public string caminhoSaida { get; set; }
        public string caminhoRaiz { get; set; }
        public Nullable<int> ProjetoId { get; set; }
        public string ProjetoNome { get; set; }
        public Nullable<bool> @lock { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string caminhoArquivo { get; set; }
    }
}
