//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication18
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indice
    {
        public string Indice1 { get; set; }
        public string Valor { get; set; }
        public int Id { get; set; }
        public int IdLog { get; set; }
    
        public virtual LogOcr LogOcr { get; set; }
    }
}
