//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication18
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogOcr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LogOcr()
        {
            this.ControleQualidadeLog = new HashSet<ControleQualidadeLog>();
            this.Indice1 = new HashSet<Indice>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Resultado { get; set; }
        public string nome { get; set; }
        public string Motor { get; set; }
        public string Modelo { get; set; }
        public string IdDocumento { get; set; }
        public string Indice { get; set; }
        public Nullable<int> ProjetoId { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public string usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControleQualidadeLog> ControleQualidadeLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Indice> Indice1 { get; set; }
    }
}
