//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication18
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrientacaoDocumento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrientacaoDocumento()
        {
            this.Tipo_Regex_Extracao = new HashSet<Tipo_Regex_Extracao>();
        }
    
        public int Id { get; set; }
        public Nullable<int> x { get; set; }
        public Nullable<int> y { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<int> IdModelo { get; set; }
        public string nome { get; set; }
        public string Palavra { get; set; }
        public Nullable<int> Tamanho { get; set; }
        public Nullable<bool> SomenteNumeros { get; set; }
        public string Regex { get; set; }
        public Nullable<bool> Barcode { get; set; }
        public Nullable<bool> QrCode { get; set; }
        public Nullable<bool> Evento { get; set; }
        public string PARAMETROENTRADA { get; set; }
        public string EspacoBranco { get; set; }
    
        public virtual Modelo Modelo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tipo_Regex_Extracao> Tipo_Regex_Extracao { get; set; }
    }
}
