//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication18
{
    using System;
    using System.Collections.Generic;
    
    public partial class PALAVRA_ORIENTACAO
    {
        public int ID { get; set; }
        public Nullable<int> IDPALAVRA { get; set; }
        public Nullable<int> IDORIENTACAO { get; set; }
        public Nullable<int> IDDOCUMENTO { get; set; }
        public string IDREGISTRO { get; set; }
    }
}
