//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication18
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entidade : DbContext
    {
        public Entidade()
            : base("name=Entidade")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CONFIGURACAO> CONFIGURACAO { get; set; }
        public virtual DbSet<ControleQualidadeLog> ControleQualidadeLog { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<Documento> Documento { get; set; }
        public virtual DbSet<documentocaptura> documentocaptura { get; set; }
        public virtual DbSet<Eventos> Eventos { get; set; }
        public virtual DbSet<Export> Export { get; set; }
        public virtual DbSet<Indice> Indice { get; set; }
        public virtual DbSet<LogOcr> LogOcr { get; set; }
        public virtual DbSet<Mensagem> Mensagem { get; set; }
        public virtual DbSet<Modelo> Modelo { get; set; }
        public virtual DbSet<ModeloProcessamento> ModeloProcessamento { get; set; }
        public virtual DbSet<OrientacaoDocumento> OrientacaoDocumento { get; set; }
        public virtual DbSet<PALAVRA_ORIENTACAO> PALAVRA_ORIENTACAO { get; set; }
        public virtual DbSet<Palavras> Palavras { get; set; }
        public virtual DbSet<PalavrasCoordenadasDocumento> PalavrasCoordenadasDocumento { get; set; }
        public virtual DbSet<PARAMETROENTRADA> PARAMETROENTRADA { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<ProcessarTreinamento> ProcessarTreinamento { get; set; }
        public virtual DbSet<PROJETO> PROJETO { get; set; }
        public virtual DbSet<PROJETO_MODELO> PROJETO_MODELO { get; set; }
        public virtual DbSet<Projeto_modelo_evento> Projeto_modelo_evento { get; set; }
        public virtual DbSet<Projeto_Usuario> Projeto_Usuario { get; set; }
        public virtual DbSet<Tipo_Regex_Extracao> Tipo_Regex_Extracao { get; set; }
        public virtual DbSet<TipoExtracao> TipoExtracao { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
