//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication18
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJETO_MODELO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROJETO_MODELO()
        {
            this.Projeto_modelo_evento = new HashSet<Projeto_modelo_evento>();
            this.Tipo_Regex_Extracao = new HashSet<Tipo_Regex_Extracao>();
        }
    
        public int ID { get; set; }
        public int PROJETO_ID { get; set; }
        public int MODELO_ID { get; set; }
        public string Padrao { get; set; }
        public Nullable<bool> ControleQualidade { get; set; }
    
        public virtual Modelo Modelo { get; set; }
        public virtual PROJETO PROJETO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projeto_modelo_evento> Projeto_modelo_evento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tipo_Regex_Extracao> Tipo_Regex_Extracao { get; set; }
    }
}
