//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication18
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJETO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROJETO()
        {
            this.Projeto_Usuario = new HashSet<Projeto_Usuario>();
            this.PROJETO_MODELO = new HashSet<PROJETO_MODELO>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public int ConfiguracaoID { get; set; }
        public string Descricao { get; set; }
        public Nullable<bool> agrupamento { get; set; }
        public Nullable<int> exportId { get; set; }
        public Nullable<bool> utilizarMineracao { get; set; }
        public string arquivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projeto_Usuario> Projeto_Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJETO_MODELO> PROJETO_MODELO { get; set; }
    }
}
