//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication18
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projeto_Usuario
    {
        public int Id { get; set; }
        public int IdProjeto { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    
        public virtual PROJETO PROJETO { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
